export const Songs = [
  {
    songs: [
      {
        songName: "Chaleya",
        sourceName: "YouTube Music",
        addedDate: "2023-12-06",
        songUrl: "audio/chaleya.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "Partial to Full Linear Development Structure ",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song1.mp3",
        image: "image/image3.webp",
      },
      {
        songName: "Mirror",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song2.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "The King_Medium",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song3.mp3",
        image: "image/image3.webp",
      },
      {
        songName: "Epic Cinematic Intro_26sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song4.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "Epic Cinematic Intro_Medium 2",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song5.mp3",
        image: "image/image3.webp",
      },
      {
        songName: "The King_60sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song6.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "Epic Cinematic Intro_Medium 1",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song7.mp3",
        image: "image/imagw2.jpg",
      },
      {
        songName: "Epic Cinematic Intro_60sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song8.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "The King_30sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song9.mp3",
        image: "image/imagw2.jpg",
      },
      {
        songName: "Epic Cinematic Intro_60sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song8.mp3",
        image: "image/image1.jpg",
      },
      {
        songName: "The King_30sec",
        sourceName: "Pixaboy",
        addedDate: "2023-12-06",
        songUrl: "audio/song9.mp3",
        image: "image/imagw2.jpg",
      },
    ],
  },
];
